### ISSUE TITLE
writing +&? etc. in a shout is making the shout get canceled

### ISSUE THREAD

**Issue by BrandonCopley** [anthonator/skittles#7] opened 2013-04-15 15:55 UTC
I tried url encoding, but that didn't seem to work.  Any ideas?

**Comment by BrandonCopley** [comment] 2013-04-15 15:58
Well not canceled but if I write this "apples & oranges" only "apples " gets shared

**Comment by anthonator** [comment] 2013-04-15 16:20
If you take a look at the paramify method in the request you'll see that all params are concatenated together using an ampersand and then URI encoded as part of the payload body sent to Foursquare. That's probably where the issue is occurring. The problem is that URI::encode doesn't escape the ampersand. Although, CGI::escape does so I may need to use a combination of the two.

https://github.com/anthonator/skittles/blob/master/lib/skittles/request.rb

**Comment by BrandonCopley** [comment] 2013-04-17 15:32
I see that you pushed some updates, unsure if you tried to fix this or not.  I might spend some time on this today with a pull request.

**Comment by anthonator** [comment] 2013-04-17 15:40
I just committed a fix. If you could pull master and make sure it works I'd appreciate it.

**Comment by BrandonCopley** [comment] 2013-04-17 15:52
So this is the same issue I was having earlier

"Apples %26 oranges - Love %23fashion%3F Follow %40HeelStruck on %40QWIQQ%21 Free http%3A%2F%2Fqwiqq.me%2Fposts%2F12471" is being posted to foursquare.

**Comment by BrandonCopley** [comment] 2013-04-17 15:57
It appears that we should use:

.to_query

instead of uri encode.

**Comment by anthonator** [comment] 2013-04-17 16:11
https://github.com/anthonator/skittles/pull/8

**Closed as completed** 2013-05-13 12:13 UTC
